### PR TITLE
add release workflow

### PR DESCRIPTION
**Pull request by CaselIT**
@zzzeek

### CODE REVIEW

**Comment by CaselIT** [comment]
uff it does not work since the version is not in the setup. one moment

**Comment by zzzeek** [comment]
thanks!

**Comment by zzzeek** [comment]
i pushed a tag rel_0_5_6 and nothign happened.  i just ran the workflow manually.

**Comment by zzzeek** [comment]
it did work though!

**Comment by zzzeek** [comment]
what happened?  https://github.com/sqlalchemyorg/changelog/releases/tag/v  what's that and how do we fix it?

**Comment by CaselIT** [comment]
I had yet to fix it

**Comment by zzzeek** [comment]
ok i just manually fixed the tag / release / etc.

do i push in v1.5.6 form or rel_1_5_6 form ?

**Comment by CaselIT** [comment]
sorry I removed them and re-created the tags. not it works

regarding how it works, just go to the actions page, then run the the workflow from there.
by default it will increase the version by one (so 0.5.6 -> 0.5.7 etc.) or provide a custom version. The release will do a tag, a release, publish to pypi and update the version on the file

so no need to create tags locally and push them

**Comment by zzzeek** [comment]
i LIKE that!   we should start thinking about this for the main projects SQLA / alembic etc.  there's more elaborate scripting to run though, generate the docs, update changelog file etc

**Comment by CaselIT** [comment]
this is taken from the stub repo. it has worked great so far https://github.com/sqlalchemy/sqlalchemy2-stubs/actions/workflows/release.yaml

**Comment by CaselIT** [comment]
> we should start thinking about this for the main projects SQLA / alembic

I think it could be doable

**Pull request merged**
