### PR TITLE
Add option to hide tags in entries

### PR DESCRIPTION
**Pull request by pieterlexis**
This also moves the permalink to the end of the sentence in that case.

Also posted to the bit bucket fork

### CODE REVIEW

**Comment by zzzeek** [comment]
this looks pretty clean  ,@caselit any comments?

**Review by CaselIT — APPROVED** [review]
Seems to be fine. Thanks!

**Comment by zzzeek** [comment]
@CaselIT how hard is it to add "release on tag" for this repo ?

**Comment by CaselIT** [comment]
not hard, mostly copy paste. let me try later

**Pull request merged**
